a=12             #a is an integer number

b=8.09           #b is an floATING number

c="prajwal"      #c is an string 

d=False          #d is an boolean variable

e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e=None           #e is none type variable (variable doesnt have anything )
e
'''
rules for defining a variables 

* a variable can contain alphabets ,digits,and underscore .
* a variable name can only start with alphabets and underscore.
* a variable name can't  start with a digit 
* can't use whitespace inside the variables .

'''

#for exAMPLE

name="prajwal"      #it is an rules valis
prajwal="ok"        #it is an rules valid
#@myself="ninja"      #it is an rules  invalids.
_hello="yeap"       #it is an rules valid




